<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container41ixvUc\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container41ixvUc/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container41ixvUc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container41ixvUc\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container41ixvUc\srcApp_KernelProdContainer([
    'container.build_hash' => '41ixvUc',
    'container.build_id' => 'f7602932',
    'container.build_time' => 1609849244,
], __DIR__.\DIRECTORY_SEPARATOR.'Container41ixvUc');
