<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBd8ix8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBd8ix8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBd8ix8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBd8ix8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJBd8ix8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JBd8ix8',
    'container.build_id' => 'e0a14dbc',
    'container.build_time' => 1609849248,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBd8ix8');
